import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  docs: [
    "introduction",
    {
      type: "category",
      label: "Installing",
      items: [
        "quickstart",
        "config-s3gw",
        "helm-charts",
        "s3gw-with-k3s",
        "s3gw-with-k8s",
      ],
    },
    {
      type: "category",
      label: "Usage",
      items: ["advanced-usage", "metrics", "troubleshoot-s3gw"],
    },
    {
      type: "category",
      label: "Development",
      items: ["s3gw-repos", "contributing", "developing", "testing", "ui"],
    },
    "roadmap",
    "s3-compatibility-table",
  ],
};

export default sidebars;
